ktor:
  profile: dev

  dev:
    db:
      url: 'jdbc:h2:./h2db/buttonfootball'
      driver: org.h2.Driver
      user: sa
      password: buttonfootball

  prod:
    db:
      url: 'jdbc:h2:tcp://button-football-1013778508330.us-central1.run.app:9092/app/h2db/buttonfootball'
      driver: org.h2.Driver
      user: sa
      password: buttonfootball

  application:
    modules:
      - com.talestonini.ApplicationKt.module

  deployment:
    port: 8080