ktor:
  profile: dev

  dev:
    db:
      url: $DEV_DB_URL
      driver: $DEV_DB_DRIVER
      user: $DEV_DB_USER
      password: $DEV_DB_PASSWORD

  prod:
    db:
      url: $PROD_DB_URL
      driver: $PROD_DB_DRIVER
      user: $PROD_DB_USER
      password: $PROD_DB_PASSWORD

  application:
    modules:
      - com.talestonini.ApplicationKt.module

  deployment:
    port: 8080