ktor:
  profile: dev

  dev:
    db:
      url: 'jdbc:h2:./h2/db/buttonfootball'
      driver: org.h2.Driver
      user: sa
      password: buttonfootball

  prod:
    db:
      url: 'jdbc:h2:tcp://34.67.166.86:9092/buttonfootball'
      driver: org.h2.Driver
      user: sa
      password: buttonfootball

  application:
    modules:
      - com.talestonini.ApplicationKt.module

  deployment:
    port: 8080